name: Deploy development

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy_dev:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install Bundler
      run: gem install bundler

    - name: Install gems
      run: bundle install

    - name: Build and deploy dev
      run: bundle exec fastlane deploy_dev
      env:
        MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
        MATCH_GIT_BASIC_AUTHORIZATION: '${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}'